specVersion: 0.2.0
name: clover-staking-indexer
version: 1.0.0
description: Indexer for clover staking

repository: 'https://github.com/web3go-xyz/clover-staking-indexer'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xe923f1773f4197a862cb4fc4a562f93585b26131dadbc943d524a82bbeecd2eb' #polkadot'0x5c7bd13edf349b33eb175ffae85210299e324d852916336027391536e686f267'
  endpoint: 'wss://api-ivy-elastic.clover.finance' #'wss://clover.api.onfinality.io/public-ws' 

dataSources:

  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
