specVersion: 0.2.0
name: clover-staking-indexer
version: 1.0.0
description: Indexer for clover staking

repository: 'https://github.com/web3go-xyz/clover-staking-indexer'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xe923f1773f4197a862cb4fc4a562f93585b26131dadbc943d524a82bbeecd2eb'
  endpoint: 'wss://api-ivy-elastic.clover.finance'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
